/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.cpp
 *  subm:  Plant
 *  model: Relbot_Model_Final_Si_hiltest
 *  expmt: Relbot_Model_Final_Si_hiltest
 *  date:  February 4, 2025
 *  time:  2:13:59 PM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.1.1.13146
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/


