/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.h
 *  model: RELbotSimple
 *  expmt: RELbotSimple
 *  date:  March 23, 2024
 *  time:  12:46:30 PM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.1.0.12836
 **********************************************************/

/* This file defines the functions necessary for motion profiles
   functions
*/
